name: Deployment-Academind
on: 
    pull_request:
        types:
            - opened
        branches:
            - master
            - "dev-*"
            - "feat/**"    
    workflow_dispatch:
    push:
        branches:
            - master
            - "dev-*"
            - "feat/**"
        paths-ignore:
            - '.github/workflows/*'     
jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get a Code
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Code deployed successfully!"