name: Deployment-Academind
on: [push, workflow_dispatch]
jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get a Code
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Code deployed successfully!"